version: '2'

services:
  keyvalueservice:
    image: jixer/oct2016dcc
    build:
      context: .
      dockerfile: Dockerfile
    links: 
      - db
    ports:
      - "5000:5000"
  db:
    image: mongo
