version: '2'

services:
  keyvalueservice:
    image: jixer/oct2016dcc:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
    environment:
      - REMOTE_DEBUGGING
    links: 
      - db
  db:
    image: mongo