version: '2'

services:
  statefulvaluesservice:
    image: jixer/oct2016dcc:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
    links: 
      - db
  db:
    image: mongo