version: '2'

services:
  statefulvaluesservice:
    image: jixer/statefulvaluesservice:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
