version: '2'

services:
  webapiapplication:
    image: webapiapplication:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8080:8080"
    environment:
      - REMOTE_DEBUGGING
